# -*- coding: utf-8 -*-

{
    'name': 'Request',
    'version': '15.0.1.0.0',
    'category': 'General',
    'description': 'Base Module for JIC IT projects ',
    'summary': 'Essential module for work with JIC Projects',
    'sequence': '1',
    'author': 'JIC IT Solutions',
    'license': 'LGPL-3',
    'company': 'JIC IT Solutions',
    'maintainer': 'JIC',
    'support': 'jic@gmail.com',
    'website': 'https://www.jic.com',
    'depends': ['base', 'web', 'hr'],
    'live_test_url': '',
    'data': ['security/ir.model.access.csv',
             'security/request_security.xml',
             'views/template.xml',
             'views/request_view.xml',
             'views/request_stage_view.xml',
             'reports/residence_transfer_renewal_request.xml',
             'reports/change_in_pay.xml',
             'reports/mobile_acknowledgement.xml',
             'reports/passport_acknowledgement.xml',
             'reports/passport_release_form.xml',
             'reports/salary_advance_form.xml',
             'reports/experience_letter.xml',
             'reports/vehicle_handover_form.xml',
             'reports/laptop_acknowledge_form.xml',
             'reports/employee_clearance_form.xml',
             'reports/manpower_requisition_form.xml',
             'reports/promotion_and_increment.xml',
             'reports/probation_confirmation_letter.xml',
             'reports/probation_confirmation_without_salary_letter.xml',
             'reports/promotion_letter_without_salary.xml',
             'reports/resignation_acceptance_letter.xml',
             'reports/deputation_letter.xml',
             'reports/salary_certificate.xml',
             'reports/vehicle_acknowledgment.xml',
             'reports/notification_of_leave_return.xml',
             ],

    'pre_init_hook': '',
    'installable': True,
    'application': False,
    'auto_install': False,
    'images': [],
}
